### ISSUE TITLE
grpcext as a separate package?

### ISSUE THREAD

**Issue by ofpiyush** [opentracing-contrib/python-grpc#2]
We do not use opentracing yet, but we do use the wrapper for unary and streaming server interceptors.

The new grpcio lib has support for server interceptor, but we could not get it to do things with the response.

We ended up using `grpcext` from this lib. Is it possible to make it into a separate library?

**Comment by rnburn** [comment]
This PR https://github.com/grpc/grpc/pull/13722 should have added both client and server interceptors. Did you put in an issue for the problem you're having?

I'd rather not provide a competing interceptor library. I only wrote it because grpc-python didn't have any interceptors when I started the project.

**Comment by ofpiyush** [comment]
@rnburn how would you migrate from the interceptors you created to the standard one? Whatever solution you use, will completely apply to our use case.

The problem I faced was that I could not do things like I would with a regular decorator.

Example:

```python
class FakeTimingInterceptor(grpcext.UnaryServerInterceptor):

    def intercept_unary(self, request, servicer_context, server_info, handler):
        start = time.time()
        try:
            return handler(request, servicer_context) # takes 10 seconds
        finally:
            log.info(time.time()-start) # 10
``` 


With the grpc interceptor
```python
class FakeTimingInterceptor(grpc.ServerInterceptor):

    def intercept_service(self, continuation, handler_call_details):
        start = time.time()
        try:
            return continuation(handler_call_details)  # takes 10 seconds
        finally:
            log.info(time.time()-start) # 0 <- should have been 10
```

Then I tried to hack my way into decorating the method from the response of `continuation` but `RPCHandler` would not let me set the attribute.

**Comment by rnburn** [comment]
@mehrdada -- do you know the answer to this?

**Comment by mehrdada** [comment]
@ofpiyush Are you trying to set properties of the returned object directly? This is by design. You should create your own wrapper class implementing RPCHandler interface and implement your logic there.

**Comment by ofpiyush** [comment]
@mehrdada I just want to make the equivalent of

```python
class FakeTimingInterceptor(grpcext.UnaryServerInterceptor):

    def intercept_unary(self, request, servicer_context, server_info, handler):
        start = time.time()
        try:
            return handler(request, servicer_context) # takes 10 seconds
        finally:
            log.info(time.time()-start) # 10
```

Do I need to make a handler for this as well? 

If yes, how do I override the default handler?

**Comment by mehrdada** [comment]
@ofpiyush I wrote an example here https://github.com/grpc/grpc/pull/14306 on how to decorate the actual handler. The `intercept_service` is invoked when the `RpcMethodHandler` is being looked-up, not when it is actually executed (this is useful when you want to reroute to other handlers based on request path, for example). That is why it appears to execute so fast in your code example. [I am considering to add a set of helper utility functions/classes to help with wrapping both on the client side and service side to the main library, but prefer to wait a few releases and observe users' needs to make  good API, since it will simply be a helper API on top of the current one.]

Note that for response-streaming RPCs, the call returns when the iterator is returned, and that will be the time you log. If you want to log the time till the last response gets sent, you need to wrap/add a done callback to the iterator returned by `continuation` in response_streaming mode.

**Comment by ofpiyush** [comment]
I'm more or less implementing equivalent of  few libs of go's https://github.com/grpc-ecosystem/go-grpc-middleware

In this case, `grpc-logrus`

**Comment by rnburn** [comment]
@ofpiyush -- were you able to get this to work? Can I close?

**Comment by mehrdada** [comment]
I missed this discussion--I don't know what exactly go-logrus does in that repo, but I suspect it measures the time till the end of the response stream. I think the appropriate thing to do is to simply follow my example but add a callback via `add_done_callback` on the return value when dealing with streaming responses and use that callback to mark the end of the request. I will try updating the example PR to do that when I get time, but I think you get the idea:

The following demonstrates the idea of the patch to apply to the PR:
```python
delayed_end = False
try:
    returned_behavior = behavior(request_or_iterator, servicer_context)
    if response_streaming and returned_behavior is not None:
        returned_behavior.add_done_callback(lambda x: self._collector(time.time()-start))
        delayed_end = True
    return returned_behavior
finally:
    if not delayed_end:
        self._collector(time.time()-start)
```

**Comment by ofpiyush** [comment]
@mehrdada thanks a ton for the example.

I got caught up in something at work. I haven't had the chance to try your solution out.

Might get a chance to try it through next week.

If I get stuck and can't find my way out, I'll open an issue on the gRPC repo or comment on your PR.

@rnburn thanks for hosting this discussion!

Cheers!
